# Generated by Django 3.2.6 on 2021-08-05 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 8, 5, 16, 8, 29, 308097)),
        ),
    ]
